### PR TITLE
rv64: fix softfloat-fp

### PR DESCRIPTION
**Pull request by AugustusWillisWang**
Now NEMU, using softfloat, is able to pass `rv64uf` and `rv64ud` in riscv-tests

### CODE REVIEW

**Comment by sashimi-yzh** [comment]
Why we need to add a new rule `all-shared` in `resource/softfloat/Makefile`? It seems that you only add a new option `-shared` to gcc, but it is an option for linking, and it should not affect the compling with `-c`.

So do you encounter any errors with `-shared` removed in the softfloat repo?

**Comment by sashimi-yzh** [comment]
It seems that we only need to add `-fPIC` to softfloat when building NEMU as an shared object.

**Comment by sashimi-yzh** [comment]
@AugustusWillisWang Please try my new commit.

**Comment by AugustusWillisWang** [comment]
That's much better, thanks a lot 😂

**Review by sashimi-yzh — APPROVED** [review]

**Pull request merged**
