### PR TITLE
fix(vmvnr): vmvnr will not set vtype register, no need to check vtype.vill

### PR DESCRIPTION
**Pull request by xyyy1420**

### CODE REVIEW

**Comment by Ziyue-Zhang** [comment]
image
image

In spike, vmvnr uses require_vector(true). In require_vector(true), it checks vill.

**Comment by xyyy1420** [comment]
image

emm, but the manual says "without needing to know or change 'vl' or 'vtype'"

**Comment by Ziyue-Zhang** [comment]
https://github.com/riscv-software-src/riscv-isa-sim/issues/1302

Aswaterman thought the spec is wrong

**Comment by xyyy1420** [comment]
but now we already have these instruction which will exec at `vtype.vill == 1`,
maybe we not check `vtype.vill` for now? until both spec and gcc offcially fix this?

**Pull request closed without merging**
