### PR TITLE
fix(PR#601): fix a wrong pattern

### PR DESCRIPTION
**Pull request by xyyy1420**
#601 brings some functional issues, this pr fix it

### CODE REVIEW

**Comment by xyyy1420** [comment]
Would you mind testing with this branch? Check the problem has been fixed?

**Review by shinezyy — APPROVED** [review]

**Comment by xyyy1420** [comment]
> @poemonsense Would you mind testing with this branch? Check the problem has been fixed?

image

already fixed, check it again?

**Comment by poemonsense** [comment]
> already fixed, check it again?

Try running all tests in the `riscv-dv` directory? I just copied all cases there

**Comment by xyyy1420** [comment]
> > already fixed, check it again?
> 
> Try running all tests in the `riscv-dv` directory? I just copied all cases there

ok

**Comment by poemonsense** [comment]
> > > already fixed, check it again?
> > 
> > 
> > Try running all tests in the `riscv-dv` directory? I just copied all cases there
> 
> ok

Maybe using `-C 10000` to limit the simulation cycle.

**Comment by xyyy1420** [comment]
> > > > already fixed, check it again?
> > > 
> > > 
> > > Try running all tests in the `riscv-dv` directory? I just copied all cases there
> > 
> > 
> > ok
> 
> Maybe using `-C 10000` to limit the simulation cycle.

all test cases have passed

**Comment by poemonsense** [comment]
> all test cases have passed, logs are placed in /nfs/home/jiaxiaoyu/fix_refactor_nemu/test_logs

Thank you very much for the work. Will merge it once CI passes

**Pull request merged**
