### PR TITLE
make 'make clean' could clean softfloat, avoid the '-fpie' flag issue

### PR DESCRIPTION
**Pull request by xyyy1420**
#276

### CODE REVIEW

**Review by poemonsense — APPROVED** [review]

**Comment by poemonsense** [comment]
where is the original clean recipt?

**Comment by poemonsense** [comment]
It seems the original clean is in `scripts/build.mk`. Is it ok to add the clean in Makefile? I did not have a test. If you have tested it, feel free to merge it

**Comment by xyyy1420** [comment]
> 看来原来的干净在.可以在 Makefile 中添加 clean 吗？我没有测试。如果您已经测试过它，请随时合并它`scripts/build.mk`

在`scripts/build.mk`中添加的话，[ci](https://github.com/OpenXiangShan/NEMU/actions/runs/8275150563/job/22641642874)会说找不到clean-softfloat这个target，很奇怪

**Comment by xyyy1420** [comment]
> It seems the original clean is in . Is it ok to add the clean in Makefile? I did not have a test. If you have tested it, feel free to merge it`scripts/build.mk`

It's ok to add the clean in build.mk, could i merge it?

**Pull request merged**
