### PR TITLE
config: Increase the memory capacity and add RVV in the dual config

### PR DESCRIPTION
**Pull request by xiaokamikami**
Since the V extension implementation is enabled by default in Xiangshan, RVV is enabled by default. 
At the same time, in order to support the operation of checkpoint on multi-core, the memory and single-core config are set to the same configuration (8G MMAP).

### CODE REVIEW

**Review by Ziyue-Zhang — APPROVED** [review]

**Comment by poemonsense** [comment]
@Ziyue-Zhang Which configs are expected to be used for xiangshan master? In https://github.com/OpenXiangShan/NEMU/pull/317, @huxuan0307  is using kunminghu config. Current XiangShan maintainers should discuss and reach an agreement on this.

**Comment by Ziyue-Zhang** [comment]
> @Ziyue-Zhang Which configs are expected to be used for xiangshan master? In #317, @huxuan0307 is using kunminghu config. Current XiangShan maintainers should discuss and reach an agreement on this.

I think use configs/riscv64-dual-xs-ref_defconfig which updated in this PR is better. I checked the diffrence between riscv64-dual-xs-ref_defconfig and riscv64-dual-xs-kunminghu-ref_defconfig, only found CONFIG_MSIZE and CONFIG_USE_MMAP are different. Config riscv64-dual-xs-kunminghu-ref_defconfig only updated the setting of rvv and rvh. This PR not only updated these, also updated CONFIG_MSIZE and CONFIG_USE_MMAP with value in  riscv64-xs-ref_defconfig.

**Comment by poemonsense** [comment]
> > @Ziyue-Zhang Which configs are expected to be used for xiangshan master? In #317, @huxuan0307 is using kunminghu config. Current XiangShan maintainers should discuss and reach an agreement on this.
> 
> I think use configs/riscv64-dual-xs-ref_defconfig which updated in this PR is better. I checked the diffrence between riscv64-dual-xs-ref_defconfig and riscv64-dual-xs-kunminghu-ref_defconfig, only found CONFIG_MSIZE and CONFIG_USE_MMAP are different. Config riscv64-dual-xs-kunminghu-ref_defconfig only updated the setting of rvv and rvh. This PR not only updated these, also updated CONFIG_MSIZE and CONFIG_USE_MMAP with value in riscv64-xs-ref_defconfig.

So close that PR?

**Comment by Ziyue-Zhang** [comment]
> > > @Ziyue-Zhang Which configs are expected to be used for xiangshan master? In #317, @huxuan0307 is using kunminghu config. Current XiangShan maintainers should discuss and reach an agreement on this.
> > 
> > 
> > I think use configs/riscv64-dual-xs-ref_defconfig which updated in this PR is better. I checked the diffrence between riscv64-dual-xs-ref_defconfig and riscv64-dual-xs-kunminghu-ref_defconfig, only found CONFIG_MSIZE and CONFIG_USE_MMAP are different. Config riscv64-dual-xs-kunminghu-ref_defconfig only updated the setting of rvv and rvh. This PR not only updated these, also updated CONFIG_MSIZE and CONFIG_USE_MMAP with value in riscv64-xs-ref_defconfig.
> 
> So close that PR?

That PR also update single-core config. Can I use that PR update riscv64-xs_defconfig and riscv64-xs-ref_defconfig, but not add new kunminghu config? Too many configs is difficult for us to mantain.

**Comment by poemonsense** [comment]
> That PR also update single-core config. Can I use that PR update riscv64-xs_defconfig and riscv64-xs-ref_defconfig, but not add new kunminghu config? Too many configs is difficult for us to mantain.

Sure. It's great

**Pull request merged**
